  N = int(input())
    list = []
    #list.append(1)
    #list. append(2)
    #list.insert(1,3)
    list.insert(0,5)
    list.insert(1,10)
    list.insert(0,6)
    print(list)
    list.remove(6)
    list.append(9)
    list.append(1)
    list.sort()
    print(list)
    list.pop(3)
    list.reverse()
    print(list)